app_about:
    path: /a-propos
    controller: App\Controller\HomeController::about

app_contact:
    path: /contact
    controller: App\Controller\HomeController::contact

app_public_reservation:
    path: /reservation-publique
    controller: App\Controller\HomeController::publicReservation
    methods: [POST]

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
